# Generated by Django 4.1.7 on 2023-04-05 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_author_category_book_author_book_categiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='categiry',
            new_name='category',
        ),
    ]
