# Generated by Django 4.1.7 on 2023-04-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_bookcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': 'Author'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Book'},
        ),
        migrations.AlterModelOptions(
            name='bookcomment',
            options={'ordering': ['id'], 'verbose_name_plural': 'Book Comment'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
    ]
